### ISSUE TITLE
Add support for new frigg.yml tasks structure

### ISSUE THREAD

**Issue by relekang** [frigg/frigg-settings#6]
As mentioned in frigg/frigg-worker#113

```yaml
tasks:
  setup:
    - npm install
  tests:
    - npm test
  after_success:
    - npm run semantic-release
```

The old style still needs to be supported, however, the code that uses frigg-settings should not notice a difference.
